name: VIDAI-LMS Push Trigger

on:
  push:
    branches:
      - main
      - devops-build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # -------Checkout code-----
      - name: Checkout repository
        uses: actions/checkout@v4

  
      # ------Docker builder Setup----
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # -----Login to Docker -------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Build Docker image
        run: |
          docker build \
          --build-arg VITE_API_BASE_URL=http://72.62.227.137:8004/api \
            -f devops/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/lms-frontend:latest \
            .
      
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lms-frontend:latest

      # ------Deploy frontend to server----
      - name: Deploy to VPS 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/lms-frontend:latest

            docker stop lms-frontend || true
            docker rm lms-frontend || true

            docker run -d \
              --restart always \
              --name lms-frontend \
              -p 3002:80 \
              ${{ secrets.DOCKER_USERNAME }}/lms-frontend:latest
